# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: your-secret-token
  best_buy_api_key: <%= ENV["BEST_BUY_API_KEY"]

test:
  secret_key_base: your-secret-token
  best_buy_api_key: <%= ENV["BEST_BUY_API_KEY"]

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# if api key, isn't working, make sure that have you ENV key set
# export BEST_BUY_API_KEY="xxxx"
